[package]
name = "hoppinworld"
version = "0.1.0"
authors = ["Joël Lupien (Jojolepro) <jojolepromain@gmail.com>"]

[dependencies]
amethyst = { git = "https://github.com/jojolepro/amethyst", branch = "hoppinworld" }
amethyst_gltf = { git = "https://github.com/jojolepro/amethyst", branch = "hoppinworld" }
amethyst-extra = { git = "https://github.com/jojolepro/amethyst-extra" }
#amethyst-rhusics = { path = "../amethyst-rhusicshoppinworld" }
amethyst-rhusics = { git = "https://github.com/amethyst/amethyst-rhusics" }
serde = "1.0"
serde_derive = "1.0"
log = "0.4"
winit = "0.17.0"
partial_function = "0.4.0"
derive-new = "0.5"
specs-derive = { git = "https://github.com/jojolepro/specs", branch = "derive" }

#[patch.crates-io]
#specs = { git = "https://github.com/jojolepro/specs", features = ["common"] }
#amethyst = { git = "https://github.com/jojolepro/amethyst", branch = "hoppinworld" }

[replace]
"amethyst:0.8.0" = { git = "https://github.com/jojolepro/amethyst", branch = "hoppinworld" }
"amethyst_core:0.3.0" = { git = "https://github.com/jojolepro/amethyst", branch = "hoppinworld" }