[package]
name = "hoppinworld"
version = "0.1.0"
authors = ["Joël Lupien (Jojolepro) <jojolepromain@gmail.com>"]

[dependencies]

amethyst = { git = "https://github.com/jojolepro/amethyst", branch = "gltf2" }
amethyst_gltf = { git = "https://github.com/jojolepro/amethyst", branch = "gltf2" }
#amethyst = { git = "https://github.com/amethyst/amethyst" }
#amethyst_gltf = { git = "https://github.com/amethyst/amethyst" }


#amethyst-extra = { git = "https://github.com/jojolepro/amethyst-extra" }
amethyst-extra = { path = "../amethyst-extra" }


#amethyst-rhusics = { path = "../amethyst-rhusicshoppinworld" }
amethyst-rhusics = { git = "https://github.com/amethyst/amethyst-rhusics" }
serde = { version = "1", features = ["serde_derive"] }
log = "0.4"
winit = "0.17.0"
partial_function = "0.4.0"
derive-new = "0.5"
derive_builder = "0.6"
specs-derive = { git = "https://github.com/slide-rs/specs" }
uuid = { version = "0.7.1", features = ["v4", "serde"] }
ron = "0.4"

hoppinworlddata = { git = "https://github.com/hoppinworld/data" }

amethyst-editor-sync = "0.1.1"

[patch.crates-io]
#specs = { git = "https://github.com/jojolepro/specs", features = ["common"] }

amethyst = { git = "https://github.com/jojolepro/amethyst", branch = "gltf2" }
amethyst_core = { git = "https://github.com/jojolepro/amethyst", branch = "gltf2" }
amethyst_assets = { git = "https://github.com/jojolepro/amethyst", branch = "gltf2" }
#amethyst = { git = "https://github.com/amethyst/amethyst" }
#amethyst_core = { git = "https://github.com/amethyst/amethyst" }
#amethyst_assets = { git = "https://github.com/amethyst/amethyst" }


#collision = { git = "https://github.com/rustgd/collision-rs", features = ["serde"] }

[patch.'https://github.com/amethyst/amethyst']
amethyst = { git = "https://github.com/jojolepro/amethyst", branch = "gltf2" }
amethyst_core = { git = "https://github.com/jojolepro/amethyst", branch = "gltf2" }
amethyst_assets = { git = "https://github.com/jojolepro/amethyst", branch = "gltf2" }

#[patch.'https://github.com/rustgd/rhusics']
#rhusics-core = { git = "https://github.com/jojolepro/rhusics", branch = "defaults", features = ["serde"] }
#rhusics-ecs = { git = "https://github.com/jojolepro/rhusics", branch = "defaults", features = ["serde"] }

#[replace]
#"collision:0.18.0" = { version = "0.18", features = ["serde"] }
#"amethyst:0.8.0" = { git = "https://github.com/jojolepro/amethyst", branch = "hoppinworld" }
#"amethyst_core:0.3.0" = { git = "https://github.com/jojolepro/amethyst", branch = "hoppinworld" }
