[package]
name = "hoppinworld"
version = "0.1.0"
authors = ["Joël Lupien (Jojolepro) <jojolepromain@gmail.com>"]

[dependencies]
amethyst = { git = "https://github.com/jojolepro/amethyst", branch = "hoppinworld" }
amethyst-extra = { git = "https://github.com/jojolepro/amethyst-extra" }
amethyst-rhusics = { path = "../amethyst-rhusicshoppinworld" }
serde = "1.0"
serde_derive = "1.0"
log = "0.4"